"""Add timeline event hierarchy, IOC links, category, tag, color, assets

Revision ID: 2794661b6f9b
Revises: bd4be88a782d
Create Date: 2026-08-07 10:30:35.351735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2794661b6f9b'
down_revision = 'bd4be88a782d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_event_iocs',
    sa.Column('timeline_event_id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ),
    sa.ForeignKeyConstraint(['timeline_event_id'], ['timeline_events.id'], ),
    sa.PrimaryKeyConstraint('timeline_event_id', 'ioc_id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_timezone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('color_slot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('affected_assets', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_timeline_events_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_timeline_events_parent_id', 'timeline_events', ['parent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_timeline_events_parent_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_timeline_events_parent_id'))
        batch_op.drop_column('parent_id')
        batch_op.drop_column('affected_assets')
        batch_op.drop_column('color_slot')
        batch_op.drop_column('tag')
        batch_op.drop_column('category')
        batch_op.drop_column('source_timezone')

    op.drop_table('timeline_event_iocs')
    # ### end Alembic commands ###
