"""Add alert_id to timeline events

Revision ID: 4593c0568b26
Revises: 2794661b6f9b
Create Date: 2026-08-07 11:29:20.200056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4593c0568b26'
down_revision = '2794661b6f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_timeline_events_alert_id'), ['alert_id'], unique=False)
        batch_op.create_foreign_key('fk_timeline_events_alert_id', 'alerts', ['alert_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_timeline_events_alert_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_timeline_events_alert_id'))
        batch_op.drop_column('alert_id')

    # ### end Alembic commands ###
