"""Initial schema

Revision ID: 5c15c1acf73c
Revises: 
Create Date: 2026-07-29 13:55:38.193388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c15c1acf73c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_counters',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('lookup_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lookup_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookup_values_list_name'), ['list_name'], unique=False)

    op.create_table('poll_state',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_sso_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('case_type', sa.String(length=64), nullable=True),
    sa.Column('affected_systems', sa.Text(), nullable=True),
    sa.Column('affected_users', sa.Text(), nullable=True),
    sa.Column('estimated_impact', sa.Text(), nullable=True),
    sa.Column('initial_vector', sa.Text(), nullable=True),
    sa.Column('lead_analyst_id', sa.Integer(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('board_flagged', sa.Boolean(), nullable=False),
    sa.Column('opened_date', sa.DateTime(), nullable=True),
    sa.Column('contained_date', sa.DateTime(), nullable=True),
    sa.Column('eradicated_date', sa.DateTime(), nullable=True),
    sa.Column('closed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_analyst_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_case_id'), ['case_id'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('tactic', sa.String(length=100), nullable=True),
    sa.Column('technique', sa.String(length=100), nullable=True),
    sa.Column('technique_id', sa.String(length=20), nullable=True),
    sa.Column('objective', sa.String(length=150), nullable=True),
    sa.Column('scenario', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('severity_name', sa.String(length=20), nullable=True),
    sa.Column('host_hostname', sa.String(length=255), nullable=True),
    sa.Column('host_ip', sa.String(length=50), nullable=True),
    sa.Column('host_platform', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('cs_created_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_alert_source_external_id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_case_id'), ['case_id'], unique=False)

    op.create_table('case_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_status_history_case_id'), ['case_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=64), nullable=True),
    sa.Column('source_system', sa.String(length=256), nullable=True),
    sa.Column('hash_md5', sa.String(length=32), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('collected_by', sa.String(length=128), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('storage_location', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('chain_of_custody', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_evidence_id'), ['evidence_id'], unique=True)

    op.create_table('iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('ioc_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iocs_case_id'), ['case_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_artifact', sa.String(length=256), nullable=True),
    sa.Column('mitre_tactic', sa.String(length=64), nullable=True),
    sa.Column('mitre_technique', sa.String(length=128), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=16), nullable=True),
    sa.Column('ioc_reference', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_case_id'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iocs_case_id'))

    op.drop_table('iocs')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_case_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('case_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_status_history_case_id'))

    op.drop_table('case_status_history')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_case_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_source'))
        batch_op.drop_index(batch_op.f('ix_alerts_external_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_case_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_case_id'))

    op.drop_table('cases')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('poll_state')
    with op.batch_alter_table('lookup_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookup_values_list_name'))

    op.drop_table('lookup_values')
    op.drop_table('id_counters')
    # ### end Alembic commands ###
