"""Add evidence file storage columns

Revision ID: bd4be88a782d
Revises: 5c15c1acf73c
Create Date: 2026-08-07 09:17:29.614275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4be88a782d'
down_revision = '5c15c1acf73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('hash_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hash_verified_ok', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_column('hash_verified_ok')
        batch_op.drop_column('hash_verified_at')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
